quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:default
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Swagger Petstore
quarkus.smallrye-openapi.info-version=1.0.7
quarkus.smallrye-openapi.info-description=Petstore-compatible API implemented on top of the existing Quarkus project structure.
